# Generated by Django 5.2.4 on 2025-07-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Nostalgic', 'Nostalgic')], default='Happy', max_length=20),
            preserve_default=False,
        ),
    ]
